module.exports={
    configureWebpack:{
        alias:{
            'assets':'@/assets',
            'network':'@/network',
            'components':'@/components',
            'views':'#/views'
        }
    }
}